server:
  port: 9084
spring:
  main:
    web-application-type: none
  rabbitmq:
    host: ${ENGINE_API_RABBITMQ_HOST_NAME:rabbitmq}
    port: ${ENGINE_API_RABBITMQ_HOST_PORT:5672}
    username: ${ENGINE_API_RABBITMQ_USERNAME:admin}
    password: ${ENGINE_API_RABBITMQ_PASSWORD:admin}
  cloud:
    stream:
      bindings:
        consumeUnprocessedIdentity-in-0:
          destination: unprocessed-identity
          group: unprocessed-group
          contentType: application/json
        consumeUnprocessedIdentity-out-0:
          destination: processed-identity
          contentType: application/json

management:
  endpoints:
    web:
      exposure.include: metrics, info, health, beans
  endpoint:
    metrics:
      enabled: true
    health:
      show-details: always


logging:
  level:
    org.springframework.cloud.stream: DEBUG
    org.springframework.integration: DEBUG
    org.springframework.amqp.rabbit: DEBUG